<div class="about-parlex" id="about">
    <section class="parlex7-back">
        <div class="w-container">
            <div id="about-animation">
                <div class="wrap">
                  <div class="about">
                      <h1 class="about-heading">ABOUT</h1>
                      <div class="about-text">WHO WE ARE ?</div>
                      <div class="sepreater"></div>
                  </div>
                  <p class="about-des">King David Fineries produces unique and bespoke vapor cocktails that are catered to the most discerning of palates and cannot be found anywhere.
                  </p>
                  <img class="about-img" src="../../../../../../../skin/frontend/rb/default/images/vapes.jpg"
                  alt="52de15aa5d3566c14300015e_about.png">
                </div>
            </div>
        </div>
    </section>
</div>