
<div class="contact-parlex" id="contact">
    <div class="parlex8-back">
        <div class="w-container">
            <div class="wrap">
                <div class="contact-div">
                    <h1 class="contact-heading">CONTACT US</h1>
                    <div class="sepreater"></div>
                </div>
            </div>
            <div id="map-canvas" class="w-widget w-widget-map contac-map" ></div>
            <div class="w-container">
                <div class="w-row contact-col">
                    <div class="w-col w-col-4 contact-col1">
                        <div>
                            <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
                               <a href="#set-5" class="hi-icon hi-icon-earth">Partners</a>
                            </div>
                            <h4 class="contact-col-head">Visit Us</h4>
                        </div>
                        <div>
                            <div class="contact-col-text">4K Bellagio 3, Bonifacio Global City, Taguig City </div>
                        </div>
                    </div>
                    <div class="w-col w-col-4 contact-col2">
                        <div>
                           <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a" onclick="showForm('mail_us_form', 'modalOverlay')">
                               <a href="#set-5" class="hi-icon hi-icon-mail">Partners</a>
                            </div>
                            <h4 class="contact-col-head">Mail us</h4>
                        </div>
                        <div>
                            <div class="contact-col-text">general: abc@xyz.com
                            <br>support: abc@xyz.com</div>
                        </div>
                    </div>
                    <div class="w-col w-col-4 contact-col3">
                        <div>
                            <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
                                <a href="#set-5" class="hi-icon hi-icon-mobile">Partners</a>
                            </div>
                          <h4 class="contact-col-head">Call Us</h4>
                        </div>
                        <div>
                            <div class="contact-col-text-bar-last">
                                P: (999) 999-9999
                                <br>
                                F: (999) 999-9999
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    function showForm(formId, overlayId) {
        console.log('form', formId);
        console.log('overlay', overlayId);
        jQuery("#" + formId).show();
        jQuery("#" + overlayId).show();
    }

    function closeForm(formId, overlayId) {
        console.log('form', formId);
        console.log('overlay', overlayId);
        jQuery("#" + formId).hide();
        jQuery("#" + overlayId).hide();
    }

    function submitMail() {
        jQuery("#contactForm").submit(function(e) {
            var postData = jQuery(this).serializeArray();
                var formURL = jQuery(this).attr("action");
                jQuery.ajax(
                {
                    url : formURL,
                    type: "POST",
                    data : postData,
                    success:function(data, textStatus, jqXHR) 
                    {
                        //data: return data from server
                        jQuery("#contact_us_message").html('<ul class="messages"><li class="success-msg"><ul><li><span>We\'ll take a look at your message and will try to send you a response about it.</span></li></ul></li></ul>');
                        jQuery("#contact_us_message").delay(5000).fadeOut();
                    },
                    error: function(jqXHR, textStatus, errorThrown) 
                    {
                        //if fails      
                        console.log('error', errorThrown);
                    }
                });
                e.preventDefault(); //STOP default action
                e.unbind(); //unbind. to stop multiple form submit.

        })
       //jQuery("#contactForm").submit();
    }
</script>