
<div class="contact-parlex" id="contact">
    <div class="parlex8-back">
        <div class="w-container">
            <div class="wrap">
                <div class="contact-div">
                    <h1 class="contact-heading">CONTACT US</h1>
                    <div class="sepreater"></div>
                </div>
            </div>
            <div id="map-canvas" class="w-widget w-widget-map contac-map" ></div>
            <div class="w-container">
                <div class="w-row contact-col">
                    <div class="w-col w-col-4 contact-col1">
                        <div>
                            <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
                               <a href="#set-5" class="hi-icon hi-icon-earth">Partners</a>
                            </div>
                            <h4 class="contact-col-head">Visit Us</h4>
                        </div>
                        <div>
                            <div class="contact-col-text">4K Bellagio 3, Bonifacio Global City, Taguig City </div>
                        </div>
                    </div>
                    <div class="w-col w-col-4 contact-col2">
                        <div>
                           <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
                               <a href="#set-5" class="hi-icon hi-icon-mail">Partners</a>
                            </div>
                            <h4 class="contact-col-head">Mail us</h4>
                        </div>
                        <div>
                            <div class="contact-col-text">general: abc@xyz.com
                            <br>support: abc@xyz.com</div>
                        </div>
                    </div>
                    <div class="w-col w-col-4 contact-col3">
                        <div>
                            <div class="hi-icon-wrap hi-icon-effect-5 hi-icon-effect-5a">
                                <a href="#set-5" class="hi-icon hi-icon-mobile">Partners</a>
                            </div>
                          <h4 class="contact-col-head">Call Us</h4>
                        </div>
                        <div>
                            <div class="contact-col-text-bar-last">
                                P: (999) 999-9999
                                <br>
                                F: (999) 999-9999
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>