<div class="intro">
	<div class="div-wrapper">
		<div class="logo-intro">
			<img class="animated slideInDown" src="skin/frontend/rb/default/images/logo.png">		
			<h1 class="animated slideInUp">KING DAVID PH</h1>
		</div>
	</div>
</div>
<div class="clouds">
	<div class="lower-clouds animated"></div>
	<div class="div-wrapper">
		<div class="grey-clouds animated slideInLeft">
			<img src="skin/frontend/rb/default/images/clouds/1.png" class="img1">
	        <img src="skin/frontend/rb/default/images/clouds/2.png" class="img2">
	        <img src="skin/frontend/rb/default/images/clouds/4.png" class="img4">
	        <img src="skin/frontend/rb/default/images/clouds/5.png" class="img5">
		</div>
		<div class="middle-clouds animated slideInRight">
	        <img src="skin/frontend/rb/default/images/clouds/6.png">
	        <img src="skin/frontend/rb/default/images/clouds/7.png" >
	        <img src="skin/frontend/rb/default/images/clouds/9.png">
	        <img src="skin/frontend/rb/default/images/clouds/8.png">
	        <img src="skin/frontend/rb/default/images/clouds/9.png">
	        <img src="skin/frontend/rb/default/images/clouds/7.png">
	        <img src="skin/frontend/rb/default/images/clouds/6.png">
		</div>
		<div class="higher-clouds animated slideInLeft">
			<img src="skin/frontend/rb/default/images/clouds/11.png">
           	<img src="skin/frontend/rb/default/images/clouds/10.png">
           	<img src="skin/frontend/rb/default/images/clouds/13.png">
           	<img src="skin/frontend/rb/default/images/clouds/15.png">
		</div>
	</div>
</div>