<section class="service-parlex" id="product">
    <section class="parlex-back">
      <div class="w-container">
        <div class="wrap">
          <div class="service-combo">
            <div class="services">
              <h1 class="service-heading">Products</h1>
              <div class="services-text">WHAT DO WE HAVE?</div>
              <div class="sepreater service"></div>
            </div>
            <div class="services-text">“ THE FIRST AND ONLY COCKTAIL E-LIQUID PRODUCT IN THE PHILIPPINES ”
              <br>SELECT PRODUCT BY CLICKING THE IMAGE</div>
            <div class="w-row">
              <div class="w-col w-col-3 services-column">
                <div class="service-icon">
                  <img src="../../../../../../../skin/frontend/rb/default/images/products/orange_vape.png">
                </div>
                <h4 class="service-head">Orange Flavor</h4>
              </div>
              <div class="w-col w-col-3">
                <div class="service-icon">
                  <img src="../../../../../../../skin/frontend/rb/default/images/products/grapes_vape.png">
                </div>
                <h4 class="service-head">Grapes Flavor</h4>
              </div>
              <div class="w-col w-col-3">
                                <div class="service-icon">
                  <img src="../../../../../../../skin/frontend/rb/default/images/products/mint_vape.png">
                </div>
                <h4 class="service-head">Mint Flavor</h4>
              </div>
              <div class="w-col w-col-3">
                <div class="service-icon">
                  <img src="../../../../../../../skin/frontend/rb/default/images/products/strawberry_vape.png">
                </div>
                <h4 class="service-head">Strawberry Vape</h4>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
</section>