<div style="width:100%;" class="error">
	<h1 style="margin-top: 120px;">Oops! This page is a little bit exhausting.</h1>
    <img src="skin/frontend/rb/default/images/smoke.gif" style="margin: 0 auto;width: 300px;display: block;">
 	<h4 style="margin-top: 10px"><a href="javascript:window.history.back();" style="color: #0F0C15;text-decoration: none;padding: 5px 10px;background-color: #69A2D4;border-radius: 3px;border: 1px solid #376C9A;box-shadow: 0px 3px 1px 1px rgba(0, 0, 0, 0.33);">Let's go and have a drink somewhere. C'mon</a></h4>
</div>